# config file version
apiVersion: 1

# # list of datasources to insert/update depending
# # on what's available in the database
datasources:
  - name: InfluxDB-2
    type: influxdb
    access: proxy
    url: http://$INFLUX_HOST_v2:8086
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    jsonData:
      version: Flux
      organization: $DOCKER_INFLUXDB_INIT_ORG
      defaultBucket: $DOCKER_INFLUXDB_INIT_BUCKET
