version: '3.6'
services:

  telegraf:
    #image: telegraf:1.20.2-alpine
    build:
      context: ./telegraf
      args:
        HTTPS_PROXY: $HTTPS_PROXY
    container_name: lrm-telegraf
    ports:
      - 57500:57500
    hostname: telegraf
    command: telegraf --watch-config poll --config-directory /etc/telegraf/telegraf.d
    volumes:
      - "./telegraf/telegraf-sample.conf:/etc/telegraf/telegraf.conf:ro"
      - "./telegraf/telegraf.d:/etc/telegraf/telegraf.d:ro"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - influxdb
    restart: always

  influxdb:
    image: influxdb:2.0.4-alpine
    container_name: lrm-influxdb
    ports:
      - 8086:8086
    env_file:
      - .env
    restart: always

  grafana:
    image: grafana/grafana:8.3.0
    container_name: lrm-grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards:ro
    env_file:
      - .env
    environment:
      # Grafana has to use Proxy mode for a successful connection;
      # Therefore, one accesses InfluxDB through the host network.
      INFLUX_HOST_v2: $HOST
    depends_on:
      - influxdb
    restart: always