# Copyright 2020-2022 Cisco Systems Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#                  xrd-10                  xrd-4
#                /        \              /       \
#               /          \            /         \
#  lx1 --- xrd-1 - xrd-2 - srd-3 - xrd-4 - xrd-5 - xrd-6 --- lx2


# IP addresses
# lx1:               10.1.1.2
# xrd-1-GE0 (left ): 10.1.1.3
# xrd-2-GE2 (right): 10.3.1.2
# lx2:               10.3.1.3

services:
  # Linux containers
  lx1:
    non_xr: true
    image: alpine:3.15
    container_name: lx1
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    command: /bin/sh -c "ip route add 99.0.0.0/8 via 99.1.100.1 && /bin/sh"
    networks:
      xrd-1-lx1:
        ipv4_address: 99.1.100.100
  lx2:
    non_xr: true
    image: alpine:3.15
    container_name: lx2
    stdin_open: true
    tty: true
    networks:
      xrd-6-lx2:
        ipv4_address: 99.6.200.200
    cap_add:
      - NET_ADMIN
    command: /bin/sh -c "ip route add 99.0.0.0/8 via 99.6.200.6 && /bin/sh"
  # XRd containers
  xrd-1:
    xr_startup_cfg: xrd-1-startup.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Mg0/RP0/CPU0/0
    networks:
      xrd-1-lx1:
        ipv4_address: 99.1.100.1

  xrd-2:
    xr_startup_cfg: xrd-2-startup.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Mg0/RP0/CPU0/0

  xrd-3:
    xr_startup_cfg: xrd-3-startup.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Mg0/RP0/CPU0/0

  xrd-4:
    xr_startup_cfg: xrd-4-startup.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Mg0/RP0/CPU0/0

  xrd-5:
    xr_startup_cfg: xrd-5-startup.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Mg0/RP0/CPU0/0

  xrd-6:
    xr_startup_cfg: xrd-6-startup.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Mg0/RP0/CPU0/0
    networks:
      xrd-6-lx2:
        ipv4_address: 99.6.200.6

  xrd-10:
    xr_startup_cfg: xrd-10-startup.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Mg0/RP0/CPU0/0

  xrd-11:
    xr_startup_cfg: xrd-11-startup.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Mg0/RP0/CPU0/0

xr_l2networks:
  - ["xrd-1:Gi0/0/0/1", "xrd-10:Gi0/0/0/0"]
  - ["xrd-1:Gi0/0/0/2", "xrd-2:Gi0/0/0/0"]
  - ["xrd-2:Gi0/0/0/1", "xrd-3:Gi0/0/0/0"]
  - ["xrd-3:Gi0/0/0/1", "xrd-10:Gi0/0/0/1"]
  - ["xrd-3:Gi0/0/0/2", "xrd-4:Gi0/0/0/0"]
  - ["xrd-4:Gi0/0/0/1", "xrd-11:Gi0/0/0/0"]
  - ["xrd-4:Gi0/0/0/2", "xrd-5:Gi0/0/0/0"]
  - ["xrd-5:Gi0/0/0/1", "xrd-6:Gi0/0/0/0"]
  - ["xrd-6:Gi0/0/0/1", "xrd-11:Gi0/0/0/1"]

networks:
  mgmt:
    xr_interfaces:
      - xrd-1:Mg0/RP0/CPU0/0
      - xrd-2:Mg0/RP0/CPU0/0
      - xrd-3:Mg0/RP0/CPU0/0
      - xrd-4:Mg0/RP0/CPU0/0
      - xrd-5:Mg0/RP0/CPU0/0
      - xrd-6:Mg0/RP0/CPU0/0
      - xrd-10:Mg0/RP0/CPU0/0
      - xrd-11:Mg0/RP0/CPU0/0  
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.254
  xrd-1-lx1:
    ipam:
      config:
        - subnet: 99.1.100.0/24
          gateway: 99.1.100.254
    xr_interfaces:
      - xrd-1:Gi0/0/0/0
  xrd-6-lx2:
    ipam:
      config:
        - subnet: 99.6.200.0/24
          gateway: 99.6.200.254
    xr_interfaces:
      - xrd-6:Gi0/0/0/2